site_name: Home Buttons

repo_url: https://github.com/nplan/HomeButtons
repo_name: nplan/HomeButtons

nav:
  - Home: index.md
  - Quick Setup: setup.md

theme:
  name: material

markdown_extensions:
  - attr_list
  - md_in_html
